### ISSUE TITLE
Stops working every other day or so

### ISSUE THREAD

**Issue by DjScribblez** [aislandener/discord-deckboard#2]
About every other day or every 2 days the extension just stops working and I have to redo the deckboard configuration. Changing the Client Secret and Access Token.

**Comment by jbinventor** [comment]
The access token expires after some time period. The extension should manage the expiration and get an access token from clientID and clientSecret (at least, on every app startup). The access token should not be a configuration parameter.

The developer documentation of Discord explains how to obtain the access token from the clientID and clientSecret:
https://discord.com/developers/docs/topics/oauth2#client-credentials-grant

Hope this helps.

**Comment by Nickinatorz** [comment]
Yeah too bad, having the same.

**Comment by Sourenics** [comment]
I think I'm having this exact issue. Deckboard extension stops working after a couple of days.

**Comment by karimawii** [comment]
Same issue 🥲

**Comment by DazerGG** [comment]
same issue x2

**Comment by EeEkKOo** [comment]
same

**Comment by alexonpeace** [comment]
I don't think this issue is ever going to be fixed lol 
the last updates been a year ago

**Comment by aislandener** [comment]
Hello everybody

I'm sorry for not updating the project for over 1 year, because of my work that took up all my free time to develop.

Today I performed an authentication repair.

It's not the way I wanted, but it's an interesting solution.

Instead of saving the access token and when it stops, performing the process to refresh the token, I'm just generating a new token each time the deckboard application is restarted.

Because I am using IPC communication, it does not return an update token to generate a new one.

I hope this fix is ​​enough, I'll see if I can find a better way to do this authentication.
